name: "Commit lint"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  commitlint:
    name: commitlint
    uses: nrkno/github-workflow-semantic-release/.github/workflows/workflow.yaml@9b92529c6154dd7c319bafe9e4dcb56568259d1a # v5.1.0
    permissions:
      contents: read
    with:
      runs-on: ubuntu-latest
      release-enabled: false
      lint-enabled: true
